baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Operating System'
theme = 'hugo-book'

disqusShortname = "Operating System"

enableGitInfo = true
BookSearch = true
BookComments = true
